spring:
  application:
    name: spring-lab

server:
  port: 8080

app:
  owner: Bolatbai Nursultan
  group: IT1-2405IS
  ui:
    theme: LIGHT
    items-per-page: 10
  mail:
    from: no-reply@iitu.kz
    retry-count: 3
    timeout: 5s
    enabled: true

logging:
  level:
    kz.iitu: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions